### ISSUE TITLE
sensor power meter rounded

### ISSUE THREAD

**Issue by troullll** [ddaddy/Tesla-Smart-Charging#3]
hi, how do you configure your sensor.power_in_or_out_rounded ?
i have a gauge like it on the "energy" tab, but i can't find and copypaste the yaml code...

**Comment by ddaddy** [comment]
My live data comes from a Shelly 3EM which provides a `watt` measurement for each phase of my 3 phase installation.
I combine the 3 phases together to get 1 measurement for the whole house then use this in the Smart Charging automation.

```
power_in_or_out:
  friendly_name: "Shelly Live Power In/Out"
  unit_of_measurement: 'W'
  value_template: >-
    {{ states('sensor.shellyem3_34945477ef4f_channel_a_power')|float + states('sensor.shellyem3_34945477ef4f_channel_b_power')|float + states('sensor.shellyem3_34945477ef4f_channel_c_power')|float }}

power_in_or_out_rounded:
  friendly_name: "Shelly Live Power In/Out (Rounded)"
  unit_of_measurement: 'W'
  value_template: "{{ states('sensor.power_in_or_out') | round|int }}"
```

What are you using to get access to the live number of watts going in/out of your meter?
